# Generated by Django 4.2.19 on 2025-02-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_family', models.CharField(max_length=100)),
                ('database_engine', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=50)),
                ('vcpu', models.IntegerField()),
                ('memory', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(max_length=100)),
                ('deployment_option', models.CharField(max_length=50)),
                ('license_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.CharField(choices=[('OnDemand', 'OnDemand'), ('Reserved', 'Reserved')], max_length=20)),
                ('lease_contract_length', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_option', models.CharField(blank=True, choices=[('No Upfront', 'No Upfront'), ('Partial Upfront', 'Partial Upfront'), ('All Upfront', 'All Upfront')], max_length=20, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.product')),
            ],
        ),
    ]
