# Generated by Django 4.2.19 on 2025-02-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('database_engine', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=50)),
                ('vcpu', models.IntegerField()),
                ('memory', models.FloatField()),
                ('price_per_hour', models.FloatField()),
                ('price_per_month', models.FloatField()),
                ('price_per_year', models.FloatField()),
                ('term_type', models.CharField(max_length=50)),
                ('lease_contract_length', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_option', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
