# Generated by Django 4.2.19 on 2025-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rdsinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RDSInstance',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_per_unit',
            new_name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deployment_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='license_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.AlterField(
            model_name='price',
            name='effective_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='lease_contract_length',
            field=models.CharField(blank=True, choices=[('1yr', '1 Year'), ('3yr', '3 Years')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'term_type', 'lease_contract_length', 'purchase_option')},
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='price',
            name='unit',
        ),
    ]
