# Generated by Django 4.2.19 on 2025-02-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_delete_rdsinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
