# Generated by Django 4.2.19 on 2025-02-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_price_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
