# Generated by Django 4.2.19 on 2025-02-24 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_price_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='effective_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='term_type',
            field=models.CharField(choices=[('OnDemand', 'OnDemand'), ('Reserved', 'Reserved')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='database_engine',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='instance_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='vcpu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
