# Generated by Django 4.2.19 on 2025-02-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_price_effective_date_alter_price_term_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'term_type', 'lease_contract_length', 'purchase_option', 'effective_date')},
        ),
        migrations.AlterIndexTogether(
            name='price',
            index_together={('product', 'term_type', 'effective_date')},
        ),
    ]
